name: Descomprimir zip
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -q -o EstebanTV.zip -d tmp_unzip
          rsync -a --exclude='.github' tmp_unzip/EstebanTV/ ./
          rm -rf tmp_unzip EstebanTV.zip
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Versión 2.0" || echo "sin cambios"
          git push
